// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package labrpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// LabRPCClient is the client API for LabRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LabRPCClient interface {
	Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallReply, error)
}

type labRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewLabRPCClient(cc grpc.ClientConnInterface) LabRPCClient {
	return &labRPCClient{cc}
}

func (c *labRPCClient) Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallReply, error) {
	out := new(CallReply)
	err := c.cc.Invoke(ctx, "/labrpcpb.LabRPC/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LabRPCServer is the server API for LabRPC service.
// All implementations must embed UnimplementedLabRPCServer
// for forward compatibility
type LabRPCServer interface {
	Call(context.Context, *CallRequest) (*CallReply, error)
	mustEmbedUnimplementedLabRPCServer()
}

// UnimplementedLabRPCServer must be embedded to have forward compatible implementations.
type UnimplementedLabRPCServer struct {
}

func (UnimplementedLabRPCServer) Call(context.Context, *CallRequest) (*CallReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedLabRPCServer) mustEmbedUnimplementedLabRPCServer() {}

// UnsafeLabRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LabRPCServer will
// result in compilation errors.
type UnsafeLabRPCServer interface {
	mustEmbedUnimplementedLabRPCServer()
}

func RegisterLabRPCServer(s *grpc.Server, srv LabRPCServer) {
	s.RegisterService(&_LabRPC_serviceDesc, srv)
}

func _LabRPC_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LabRPCServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/labrpcpb.LabRPC/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LabRPCServer).Call(ctx, req.(*CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LabRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "labrpcpb.LabRPC",
	HandlerType: (*LabRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _LabRPC_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "labrpcpb/labrpc.proto",
}
