// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: labrpcpb/labrpc.proto

package labrpcpb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SvcMeth string `protobuf:"bytes,1,opt,name=svc_meth,json=svcMeth,proto3" json:"svc_meth,omitempty"`
	Args    []byte `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_labrpcpb_labrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_labrpcpb_labrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_labrpcpb_labrpc_proto_rawDescGZIP(), []int{0}
}

func (x *CallRequest) GetSvcMeth() string {
	if x != nil {
		return x.SvcMeth
	}
	return ""
}

func (x *CallRequest) GetArgs() []byte {
	if x != nil {
		return x.Args
	}
	return nil
}

type CallReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok    bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reply []byte `protobuf:"bytes,2,opt,name=reply,proto3" json:"reply,omitempty"`
}

func (x *CallReply) Reset() {
	*x = CallReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_labrpcpb_labrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallReply) ProtoMessage() {}

func (x *CallReply) ProtoReflect() protoreflect.Message {
	mi := &file_labrpcpb_labrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallReply.ProtoReflect.Descriptor instead.
func (*CallReply) Descriptor() ([]byte, []int) {
	return file_labrpcpb_labrpc_proto_rawDescGZIP(), []int{1}
}

func (x *CallReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CallReply) GetReply() []byte {
	if x != nil {
		return x.Reply
	}
	return nil
}

var File_labrpcpb_labrpc_proto protoreflect.FileDescriptor

var file_labrpcpb_labrpc_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6c, 0x61, 0x62, 0x72, 0x70, 0x63, 0x70, 0x62, 0x2f, 0x6c, 0x61, 0x62, 0x72, 0x70,
	0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6c, 0x61, 0x62, 0x72, 0x70, 0x63, 0x70,
	0x62, 0x22, 0x3c, 0x0a, 0x0b, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x73, 0x76, 0x63, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x76, 0x63, 0x4d, 0x65, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x61,
	0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22,
	0x31, 0x0a, 0x09, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02,
	0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x14, 0x0a, 0x05,
	0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x72, 0x65, 0x70,
	0x6c, 0x79, 0x32, 0x3c, 0x0a, 0x06, 0x4c, 0x61, 0x62, 0x52, 0x50, 0x43, 0x12, 0x32, 0x0a, 0x04,
	0x43, 0x61, 0x6c, 0x6c, 0x12, 0x15, 0x2e, 0x6c, 0x61, 0x62, 0x72, 0x70, 0x63, 0x70, 0x62, 0x2e,
	0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x6c, 0x61,
	0x62, 0x72, 0x70, 0x63, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x42, 0x11, 0x5a, 0x0f, 0x36, 0x2e, 0x35, 0x38, 0x34, 0x30, 0x2f, 0x6c, 0x61, 0x62, 0x72, 0x70,
	0x63, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_labrpcpb_labrpc_proto_rawDescOnce sync.Once
	file_labrpcpb_labrpc_proto_rawDescData = file_labrpcpb_labrpc_proto_rawDesc
)

func file_labrpcpb_labrpc_proto_rawDescGZIP() []byte {
	file_labrpcpb_labrpc_proto_rawDescOnce.Do(func() {
		file_labrpcpb_labrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_labrpcpb_labrpc_proto_rawDescData)
	})
	return file_labrpcpb_labrpc_proto_rawDescData
}

var file_labrpcpb_labrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_labrpcpb_labrpc_proto_goTypes = []interface{}{
	(*CallRequest)(nil), // 0: labrpcpb.CallRequest
	(*CallReply)(nil),   // 1: labrpcpb.CallReply
}
var file_labrpcpb_labrpc_proto_depIdxs = []int32{
	0, // 0: labrpcpb.LabRPC.Call:input_type -> labrpcpb.CallRequest
	1, // 1: labrpcpb.LabRPC.Call:output_type -> labrpcpb.CallReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_labrpcpb_labrpc_proto_init() }
func file_labrpcpb_labrpc_proto_init() {
	if File_labrpcpb_labrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_labrpcpb_labrpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_labrpcpb_labrpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_labrpcpb_labrpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_labrpcpb_labrpc_proto_goTypes,
		DependencyIndexes: file_labrpcpb_labrpc_proto_depIdxs,
		MessageInfos:      file_labrpcpb_labrpc_proto_msgTypes,
	}.Build()
	File_labrpcpb_labrpc_proto = out.File
	file_labrpcpb_labrpc_proto_rawDesc = nil
	file_labrpcpb_labrpc_proto_goTypes = nil
	file_labrpcpb_labrpc_proto_depIdxs = nil
}
