// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package shardkvpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ShardKVClient is the client API for ShardKV service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShardKVClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error)
	Range(ctx context.Context, in *RangeRequest, opts ...grpc.CallOption) (*RangeResponse, error)
	TxnBegin(ctx context.Context, in *TxnBeginRequest, opts ...grpc.CallOption) (*TxnBeginResponse, error)
	TxnGet(ctx context.Context, in *TxnGetRequest, opts ...grpc.CallOption) (*TxnGetResponse, error)
	TxnRange(ctx context.Context, in *TxnRangeRequest, opts ...grpc.CallOption) (*TxnRangeResponse, error)
	TxnCommit(ctx context.Context, in *TxnCommitRequest, opts ...grpc.CallOption) (*TxnCommitResponse, error)
}

type shardKVClient struct {
	cc grpc.ClientConnInterface
}

func NewShardKVClient(cc grpc.ClientConnInterface) ShardKVClient {
	return &shardKVClient{cc}
}

func (c *shardKVClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/shardkvpb.ShardKV/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardKVClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, "/shardkvpb.ShardKV/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardKVClient) Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error) {
	out := new(AppendResponse)
	err := c.cc.Invoke(ctx, "/shardkvpb.ShardKV/Append", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardKVClient) Range(ctx context.Context, in *RangeRequest, opts ...grpc.CallOption) (*RangeResponse, error) {
	out := new(RangeResponse)
	err := c.cc.Invoke(ctx, "/shardkvpb.ShardKV/Range", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardKVClient) TxnBegin(ctx context.Context, in *TxnBeginRequest, opts ...grpc.CallOption) (*TxnBeginResponse, error) {
	out := new(TxnBeginResponse)
	err := c.cc.Invoke(ctx, "/shardkvpb.ShardKV/TxnBegin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardKVClient) TxnGet(ctx context.Context, in *TxnGetRequest, opts ...grpc.CallOption) (*TxnGetResponse, error) {
	out := new(TxnGetResponse)
	err := c.cc.Invoke(ctx, "/shardkvpb.ShardKV/TxnGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardKVClient) TxnRange(ctx context.Context, in *TxnRangeRequest, opts ...grpc.CallOption) (*TxnRangeResponse, error) {
	out := new(TxnRangeResponse)
	err := c.cc.Invoke(ctx, "/shardkvpb.ShardKV/TxnRange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardKVClient) TxnCommit(ctx context.Context, in *TxnCommitRequest, opts ...grpc.CallOption) (*TxnCommitResponse, error) {
	out := new(TxnCommitResponse)
	err := c.cc.Invoke(ctx, "/shardkvpb.ShardKV/TxnCommit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShardKVServer is the server API for ShardKV service.
// All implementations must embed UnimplementedShardKVServer
// for forward compatibility
type ShardKVServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Put(context.Context, *PutRequest) (*PutResponse, error)
	Append(context.Context, *AppendRequest) (*AppendResponse, error)
	Range(context.Context, *RangeRequest) (*RangeResponse, error)
	TxnBegin(context.Context, *TxnBeginRequest) (*TxnBeginResponse, error)
	TxnGet(context.Context, *TxnGetRequest) (*TxnGetResponse, error)
	TxnRange(context.Context, *TxnRangeRequest) (*TxnRangeResponse, error)
	TxnCommit(context.Context, *TxnCommitRequest) (*TxnCommitResponse, error)
	mustEmbedUnimplementedShardKVServer()
}

// UnimplementedShardKVServer must be embedded to have forward compatible implementations.
type UnimplementedShardKVServer struct {
}

func (UnimplementedShardKVServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedShardKVServer) Put(context.Context, *PutRequest) (*PutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedShardKVServer) Append(context.Context, *AppendRequest) (*AppendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedShardKVServer) Range(context.Context, *RangeRequest) (*RangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Range not implemented")
}
func (UnimplementedShardKVServer) TxnBegin(context.Context, *TxnBeginRequest) (*TxnBeginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TxnBegin not implemented")
}
func (UnimplementedShardKVServer) TxnGet(context.Context, *TxnGetRequest) (*TxnGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TxnGet not implemented")
}
func (UnimplementedShardKVServer) TxnRange(context.Context, *TxnRangeRequest) (*TxnRangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TxnRange not implemented")
}
func (UnimplementedShardKVServer) TxnCommit(context.Context, *TxnCommitRequest) (*TxnCommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TxnCommit not implemented")
}
func (UnimplementedShardKVServer) mustEmbedUnimplementedShardKVServer() {}

// UnsafeShardKVServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShardKVServer will
// result in compilation errors.
type UnsafeShardKVServer interface {
	mustEmbedUnimplementedShardKVServer()
}

func RegisterShardKVServer(s *grpc.Server, srv ShardKVServer) {
	s.RegisterService(&_ShardKV_serviceDesc, srv)
}

func _ShardKV_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardKVServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shardkvpb.ShardKV/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardKVServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardKV_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardKVServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shardkvpb.ShardKV/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardKVServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardKV_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardKVServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shardkvpb.ShardKV/Append",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardKVServer).Append(ctx, req.(*AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardKV_Range_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardKVServer).Range(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shardkvpb.ShardKV/Range",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardKVServer).Range(ctx, req.(*RangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardKV_TxnBegin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxnBeginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardKVServer).TxnBegin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shardkvpb.ShardKV/TxnBegin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardKVServer).TxnBegin(ctx, req.(*TxnBeginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardKV_TxnGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxnGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardKVServer).TxnGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shardkvpb.ShardKV/TxnGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardKVServer).TxnGet(ctx, req.(*TxnGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardKV_TxnRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxnRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardKVServer).TxnRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shardkvpb.ShardKV/TxnRange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardKVServer).TxnRange(ctx, req.(*TxnRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardKV_TxnCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxnCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardKVServer).TxnCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shardkvpb.ShardKV/TxnCommit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardKVServer).TxnCommit(ctx, req.(*TxnCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShardKV_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shardkvpb.ShardKV",
	HandlerType: (*ShardKVServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _ShardKV_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _ShardKV_Put_Handler,
		},
		{
			MethodName: "Append",
			Handler:    _ShardKV_Append_Handler,
		},
		{
			MethodName: "Range",
			Handler:    _ShardKV_Range_Handler,
		},
		{
			MethodName: "TxnBegin",
			Handler:    _ShardKV_TxnBegin_Handler,
		},
		{
			MethodName: "TxnGet",
			Handler:    _ShardKV_TxnGet_Handler,
		},
		{
			MethodName: "TxnRange",
			Handler:    _ShardKV_TxnRange_Handler,
		},
		{
			MethodName: "TxnCommit",
			Handler:    _ShardKV_TxnCommit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shardkvpb/shardkv.proto",
}
