// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: shardkvpb/shardkv.proto

package shardkvpb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type IsolationLevel int32

const (
	IsolationLevel_READ_UNCOMMITTED IsolationLevel = 0
	IsolationLevel_READ_COMMITTED   IsolationLevel = 1
	IsolationLevel_REPEATABLE_READ  IsolationLevel = 2
	IsolationLevel_SERIALIZABLE     IsolationLevel = 3
)

// Enum value maps for IsolationLevel.
var (
	IsolationLevel_name = map[int32]string{
		0: "READ_UNCOMMITTED",
		1: "READ_COMMITTED",
		2: "REPEATABLE_READ",
		3: "SERIALIZABLE",
	}
	IsolationLevel_value = map[string]int32{
		"READ_UNCOMMITTED": 0,
		"READ_COMMITTED":   1,
		"REPEATABLE_READ":  2,
		"SERIALIZABLE":     3,
	}
)

func (x IsolationLevel) Enum() *IsolationLevel {
	p := new(IsolationLevel)
	*p = x
	return p
}

func (x IsolationLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IsolationLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_shardkvpb_shardkv_proto_enumTypes[0].Descriptor()
}

func (IsolationLevel) Type() protoreflect.EnumType {
	return &file_shardkvpb_shardkv_proto_enumTypes[0]
}

func (x IsolationLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IsolationLevel.Descriptor instead.
func (IsolationLevel) EnumDescriptor() ([]byte, []int) {
	return file_shardkvpb_shardkv_proto_rawDescGZIP(), []int{0}
}

type KeyValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardkvpb_shardkv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_shardkvpb_shardkv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_shardkvpb_shardkv_proto_rawDescGZIP(), []int{0}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type TxnRangeKV struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value   string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Version uint64 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *TxnRangeKV) Reset() {
	*x = TxnRangeKV{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardkvpb_shardkv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnRangeKV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnRangeKV) ProtoMessage() {}

func (x *TxnRangeKV) ProtoReflect() protoreflect.Message {
	mi := &file_shardkvpb_shardkv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnRangeKV.ProtoReflect.Descriptor instead.
func (*TxnRangeKV) Descriptor() ([]byte, []int) {
	return file_shardkvpb_shardkv_proto_rawDescGZIP(), []int{1}
}

func (x *TxnRangeKV) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TxnRangeKV) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *TxnRangeKV) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type TxnWrite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value  string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Delete bool   `protobuf:"varint,3,opt,name=delete,proto3" json:"delete,omitempty"`
}

func (x *TxnWrite) Reset() {
	*x = TxnWrite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardkvpb_shardkv_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnWrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnWrite) ProtoMessage() {}

func (x *TxnWrite) ProtoReflect() protoreflect.Message {
	mi := &file_shardkvpb_shardkv_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnWrite.ProtoReflect.Descriptor instead.
func (*TxnWrite) Descriptor() ([]byte, []int) {
	return file_shardkvpb_shardkv_proto_rawDescGZIP(), []int{2}
}

func (x *TxnWrite) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TxnWrite) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *TxnWrite) GetDelete() bool {
	if x != nil {
		return x.Delete
	}
	return false
}

type TxnRead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Version uint64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *TxnRead) Reset() {
	*x = TxnRead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardkvpb_shardkv_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnRead) ProtoMessage() {}

func (x *TxnRead) ProtoReflect() protoreflect.Message {
	mi := &file_shardkvpb_shardkv_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnRead.ProtoReflect.Descriptor instead.
func (*TxnRead) Descriptor() ([]byte, []int) {
	return file_shardkvpb_shardkv_proto_rawDescGZIP(), []int{3}
}

func (x *TxnRead) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TxnRead) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardkvpb_shardkv_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shardkvpb_shardkv_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_shardkvpb_shardkv_proto_rawDescGZIP(), []int{4}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err   string `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardkvpb_shardkv_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shardkvpb_shardkv_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_shardkvpb_shardkv_proto_rawDescGZIP(), []int{5}
}

func (x *GetResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *GetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardkvpb_shardkv_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shardkvpb_shardkv_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_shardkvpb_shardkv_proto_rawDescGZIP(), []int{6}
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err string `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardkvpb_shardkv_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shardkvpb_shardkv_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_shardkvpb_shardkv_proto_rawDescGZIP(), []int{7}
}

func (x *PutResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type AppendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *AppendRequest) Reset() {
	*x = AppendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardkvpb_shardkv_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRequest) ProtoMessage() {}

func (x *AppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shardkvpb_shardkv_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRequest.ProtoReflect.Descriptor instead.
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return file_shardkvpb_shardkv_proto_rawDescGZIP(), []int{8}
}

func (x *AppendRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AppendRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AppendResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err string `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *AppendResponse) Reset() {
	*x = AppendResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardkvpb_shardkv_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendResponse) ProtoMessage() {}

func (x *AppendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shardkvpb_shardkv_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendResponse.ProtoReflect.Descriptor instead.
func (*AppendResponse) Descriptor() ([]byte, []int) {
	return file_shardkvpb_shardkv_proto_rawDescGZIP(), []int{9}
}

func (x *AppendResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type RangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start string `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End   string `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	Limit int32  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *RangeRequest) Reset() {
	*x = RangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardkvpb_shardkv_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeRequest) ProtoMessage() {}

func (x *RangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shardkvpb_shardkv_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeRequest.ProtoReflect.Descriptor instead.
func (*RangeRequest) Descriptor() ([]byte, []int) {
	return file_shardkvpb_shardkv_proto_rawDescGZIP(), []int{10}
}

func (x *RangeRequest) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *RangeRequest) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *RangeRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RangeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err string      `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	Kvs []*KeyValue `protobuf:"bytes,2,rep,name=kvs,proto3" json:"kvs,omitempty"`
}

func (x *RangeResponse) Reset() {
	*x = RangeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardkvpb_shardkv_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeResponse) ProtoMessage() {}

func (x *RangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shardkvpb_shardkv_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeResponse.ProtoReflect.Descriptor instead.
func (*RangeResponse) Descriptor() ([]byte, []int) {
	return file_shardkvpb_shardkv_proto_rawDescGZIP(), []int{11}
}

func (x *RangeResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *RangeResponse) GetKvs() []*KeyValue {
	if x != nil {
		return x.Kvs
	}
	return nil
}

type TxnBeginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Isolation IsolationLevel `protobuf:"varint,1,opt,name=isolation,proto3,enum=shardkvpb.IsolationLevel" json:"isolation,omitempty"`
	KeyHint   string         `protobuf:"bytes,2,opt,name=key_hint,json=keyHint,proto3" json:"key_hint,omitempty"`
}

func (x *TxnBeginRequest) Reset() {
	*x = TxnBeginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardkvpb_shardkv_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnBeginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnBeginRequest) ProtoMessage() {}

func (x *TxnBeginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shardkvpb_shardkv_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnBeginRequest.ProtoReflect.Descriptor instead.
func (*TxnBeginRequest) Descriptor() ([]byte, []int) {
	return file_shardkvpb_shardkv_proto_rawDescGZIP(), []int{12}
}

func (x *TxnBeginRequest) GetIsolation() IsolationLevel {
	if x != nil {
		return x.Isolation
	}
	return IsolationLevel_READ_UNCOMMITTED
}

func (x *TxnBeginRequest) GetKeyHint() string {
	if x != nil {
		return x.KeyHint
	}
	return ""
}

type TxnBeginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err      string `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	TxnId    uint64 `protobuf:"varint,2,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	Snapshot uint64 `protobuf:"varint,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
}

func (x *TxnBeginResponse) Reset() {
	*x = TxnBeginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardkvpb_shardkv_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnBeginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnBeginResponse) ProtoMessage() {}

func (x *TxnBeginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shardkvpb_shardkv_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnBeginResponse.ProtoReflect.Descriptor instead.
func (*TxnBeginResponse) Descriptor() ([]byte, []int) {
	return file_shardkvpb_shardkv_proto_rawDescGZIP(), []int{13}
}

func (x *TxnBeginResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *TxnBeginResponse) GetTxnId() uint64 {
	if x != nil {
		return x.TxnId
	}
	return 0
}

func (x *TxnBeginResponse) GetSnapshot() uint64 {
	if x != nil {
		return x.Snapshot
	}
	return 0
}

type TxnGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key      string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Snapshot uint64 `protobuf:"varint,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	TxnId    uint64 `protobuf:"varint,3,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
}

func (x *TxnGetRequest) Reset() {
	*x = TxnGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardkvpb_shardkv_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnGetRequest) ProtoMessage() {}

func (x *TxnGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shardkvpb_shardkv_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnGetRequest.ProtoReflect.Descriptor instead.
func (*TxnGetRequest) Descriptor() ([]byte, []int) {
	return file_shardkvpb_shardkv_proto_rawDescGZIP(), []int{14}
}

func (x *TxnGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TxnGetRequest) GetSnapshot() uint64 {
	if x != nil {
		return x.Snapshot
	}
	return 0
}

func (x *TxnGetRequest) GetTxnId() uint64 {
	if x != nil {
		return x.TxnId
	}
	return 0
}

type TxnGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err     string `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	Value   string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Version uint64 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *TxnGetResponse) Reset() {
	*x = TxnGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardkvpb_shardkv_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnGetResponse) ProtoMessage() {}

func (x *TxnGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shardkvpb_shardkv_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnGetResponse.ProtoReflect.Descriptor instead.
func (*TxnGetResponse) Descriptor() ([]byte, []int) {
	return file_shardkvpb_shardkv_proto_rawDescGZIP(), []int{15}
}

func (x *TxnGetResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *TxnGetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *TxnGetResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type TxnRangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start    string `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End      string `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	Limit    int32  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Snapshot uint64 `protobuf:"varint,4,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	TxnId    uint64 `protobuf:"varint,5,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
}

func (x *TxnRangeRequest) Reset() {
	*x = TxnRangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardkvpb_shardkv_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnRangeRequest) ProtoMessage() {}

func (x *TxnRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shardkvpb_shardkv_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnRangeRequest.ProtoReflect.Descriptor instead.
func (*TxnRangeRequest) Descriptor() ([]byte, []int) {
	return file_shardkvpb_shardkv_proto_rawDescGZIP(), []int{16}
}

func (x *TxnRangeRequest) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *TxnRangeRequest) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

func (x *TxnRangeRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TxnRangeRequest) GetSnapshot() uint64 {
	if x != nil {
		return x.Snapshot
	}
	return 0
}

func (x *TxnRangeRequest) GetTxnId() uint64 {
	if x != nil {
		return x.TxnId
	}
	return 0
}

type TxnRangeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err string        `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	Kvs []*TxnRangeKV `protobuf:"bytes,2,rep,name=kvs,proto3" json:"kvs,omitempty"`
}

func (x *TxnRangeResponse) Reset() {
	*x = TxnRangeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardkvpb_shardkv_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnRangeResponse) ProtoMessage() {}

func (x *TxnRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shardkvpb_shardkv_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnRangeResponse.ProtoReflect.Descriptor instead.
func (*TxnRangeResponse) Descriptor() ([]byte, []int) {
	return file_shardkvpb_shardkv_proto_rawDescGZIP(), []int{17}
}

func (x *TxnRangeResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *TxnRangeResponse) GetKvs() []*TxnRangeKV {
	if x != nil {
		return x.Kvs
	}
	return nil
}

type TxnCommitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxnId     uint64         `protobuf:"varint,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	Isolation IsolationLevel `protobuf:"varint,2,opt,name=isolation,proto3,enum=shardkvpb.IsolationLevel" json:"isolation,omitempty"`
	Writes    []*TxnWrite    `protobuf:"bytes,4,rep,name=writes,proto3" json:"writes,omitempty"`
	Reads     []*TxnRead     `protobuf:"bytes,5,rep,name=reads,proto3" json:"reads,omitempty"`
}

func (x *TxnCommitRequest) Reset() {
	*x = TxnCommitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardkvpb_shardkv_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnCommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnCommitRequest) ProtoMessage() {}

func (x *TxnCommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shardkvpb_shardkv_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnCommitRequest.ProtoReflect.Descriptor instead.
func (*TxnCommitRequest) Descriptor() ([]byte, []int) {
	return file_shardkvpb_shardkv_proto_rawDescGZIP(), []int{18}
}

func (x *TxnCommitRequest) GetTxnId() uint64 {
	if x != nil {
		return x.TxnId
	}
	return 0
}

func (x *TxnCommitRequest) GetIsolation() IsolationLevel {
	if x != nil {
		return x.Isolation
	}
	return IsolationLevel_READ_UNCOMMITTED
}

func (x *TxnCommitRequest) GetWrites() []*TxnWrite {
	if x != nil {
		return x.Writes
	}
	return nil
}

func (x *TxnCommitRequest) GetReads() []*TxnRead {
	if x != nil {
		return x.Reads
	}
	return nil
}

type TxnCommitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err string `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *TxnCommitResponse) Reset() {
	*x = TxnCommitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shardkvpb_shardkv_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxnCommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnCommitResponse) ProtoMessage() {}

func (x *TxnCommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shardkvpb_shardkv_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnCommitResponse.ProtoReflect.Descriptor instead.
func (*TxnCommitResponse) Descriptor() ([]byte, []int) {
	return file_shardkvpb_shardkv_proto_rawDescGZIP(), []int{19}
}

func (x *TxnCommitResponse) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_shardkvpb_shardkv_proto protoreflect.FileDescriptor

var file_shardkvpb_shardkv_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x70, 0x62, 0x2f, 0x73, 0x68, 0x61, 0x72,
	0x64, 0x6b, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x68, 0x61, 0x72, 0x64,
	0x6b, 0x76, 0x70, 0x62, 0x22, 0x32, 0x0a, 0x08, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4e, 0x0a, 0x0a, 0x54, 0x78, 0x6e, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x4b, 0x56, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x4a, 0x0a, 0x08, 0x54, 0x78, 0x6e, 0x57,
	0x72, 0x69, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x22, 0x35, 0x0a, 0x07, 0x54, 0x78, 0x6e, 0x52, 0x65, 0x61, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x1e, 0x0a, 0x0a, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x35, 0x0a, 0x0b, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x34, 0x0a, 0x0a, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1f, 0x0a, 0x0b, 0x50, 0x75, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x37, 0x0a, 0x0d, 0x41, 0x70, 0x70,
	0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x22, 0x0a, 0x0e, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x4c, 0x0a, 0x0c, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x22, 0x48, 0x0a, 0x0d, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x25, 0x0a, 0x03, 0x6b, 0x76, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x70, 0x62,
	0x2e, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x03, 0x6b, 0x76, 0x73, 0x22, 0x65,
	0x0a, 0x0f, 0x54, 0x78, 0x6e, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x37, 0x0a, 0x09, 0x69, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x70, 0x62,
	0x2e, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52,
	0x09, 0x69, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x6b, 0x65,
	0x79, 0x5f, 0x68, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65,
	0x79, 0x48, 0x69, 0x6e, 0x74, 0x22, 0x57, 0x0a, 0x10, 0x54, 0x78, 0x6e, 0x42, 0x65, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x15, 0x0a, 0x06, 0x74,
	0x78, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x78, 0x6e,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x22, 0x54,
	0x0a, 0x0d, 0x54, 0x78, 0x6e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x08, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x15, 0x0a,
	0x06, 0x74, 0x78, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74,
	0x78, 0x6e, 0x49, 0x64, 0x22, 0x52, 0x0a, 0x0e, 0x54, 0x78, 0x6e, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x82, 0x01, 0x0a, 0x0f, 0x54, 0x78, 0x6e,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x65, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x73, 0x6e,
	0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x78, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x78, 0x6e, 0x49, 0x64, 0x22, 0x4d, 0x0a,
	0x10, 0x54, 0x78, 0x6e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x65, 0x72, 0x72, 0x12, 0x27, 0x0a, 0x03, 0x6b, 0x76, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x54, 0x78, 0x6e,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x4b, 0x56, 0x52, 0x03, 0x6b, 0x76, 0x73, 0x22, 0xb9, 0x01, 0x0a,
	0x10, 0x54, 0x78, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x78, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x05, 0x74, 0x78, 0x6e, 0x49, 0x64, 0x12, 0x37, 0x0a, 0x09, 0x69, 0x73, 0x6f, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x73, 0x68,
	0x61, 0x72, 0x64, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x09, 0x69, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x2b, 0x0a, 0x06, 0x77, 0x72, 0x69, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x54, 0x78,
	0x6e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x06, 0x77, 0x72, 0x69, 0x74, 0x65, 0x73, 0x12, 0x28,
	0x0a, 0x05, 0x72, 0x65, 0x61, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x54, 0x78, 0x6e, 0x52, 0x65, 0x61,
	0x64, 0x52, 0x05, 0x72, 0x65, 0x61, 0x64, 0x73, 0x22, 0x25, 0x0a, 0x11, 0x54, 0x78, 0x6e, 0x43,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x2a,
	0x61, 0x0a, 0x0e, 0x49, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x45, 0x41, 0x44, 0x5f, 0x55, 0x4e, 0x43, 0x4f, 0x4d, 0x4d,
	0x49, 0x54, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x45, 0x41, 0x44, 0x5f,
	0x43, 0x4f, 0x4d, 0x4d, 0x49, 0x54, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x52,
	0x45, 0x50, 0x45, 0x41, 0x54, 0x41, 0x42, 0x4c, 0x45, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x10, 0x02,
	0x12, 0x10, 0x0a, 0x0c, 0x53, 0x45, 0x52, 0x49, 0x41, 0x4c, 0x49, 0x5a, 0x41, 0x42, 0x4c, 0x45,
	0x10, 0x03, 0x32, 0x81, 0x04, 0x0a, 0x07, 0x53, 0x68, 0x61, 0x72, 0x64, 0x4b, 0x56, 0x12, 0x34,
	0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x15, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x70,
	0x62, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x73,
	0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x03, 0x50, 0x75, 0x74, 0x12, 0x15, 0x2e, 0x73, 0x68,
	0x61, 0x72, 0x64, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x50,
	0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x06, 0x41, 0x70,
	0x70, 0x65, 0x6e, 0x64, 0x12, 0x18, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x70, 0x62,
	0x2e, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x41, 0x70, 0x70, 0x65, 0x6e,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x05, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x12, 0x17, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x73, 0x68,
	0x61, 0x72, 0x64, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x08, 0x54, 0x78, 0x6e, 0x42, 0x65, 0x67, 0x69,
	0x6e, 0x12, 0x1a, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x54, 0x78,
	0x6e, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x54, 0x78, 0x6e, 0x42, 0x65, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x06, 0x54, 0x78,
	0x6e, 0x47, 0x65, 0x74, 0x12, 0x18, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x70, 0x62,
	0x2e, 0x54, 0x78, 0x6e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x54, 0x78, 0x6e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x08, 0x54, 0x78, 0x6e,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1a, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x70,
	0x62, 0x2e, 0x54, 0x78, 0x6e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x54, 0x78,
	0x6e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46,
	0x0a, 0x09, 0x54, 0x78, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x1b, 0x2e, 0x73, 0x68,
	0x61, 0x72, 0x64, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x54, 0x78, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64,
	0x6b, 0x76, 0x70, 0x62, 0x2e, 0x54, 0x78, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x12, 0x5a, 0x10, 0x36, 0x2e, 0x35, 0x38, 0x34, 0x30,
	0x2f, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6b, 0x76, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_shardkvpb_shardkv_proto_rawDescOnce sync.Once
	file_shardkvpb_shardkv_proto_rawDescData = file_shardkvpb_shardkv_proto_rawDesc
)

func file_shardkvpb_shardkv_proto_rawDescGZIP() []byte {
	file_shardkvpb_shardkv_proto_rawDescOnce.Do(func() {
		file_shardkvpb_shardkv_proto_rawDescData = protoimpl.X.CompressGZIP(file_shardkvpb_shardkv_proto_rawDescData)
	})
	return file_shardkvpb_shardkv_proto_rawDescData
}

var file_shardkvpb_shardkv_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shardkvpb_shardkv_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_shardkvpb_shardkv_proto_goTypes = []interface{}{
	(IsolationLevel)(0),       // 0: shardkvpb.IsolationLevel
	(*KeyValue)(nil),          // 1: shardkvpb.KeyValue
	(*TxnRangeKV)(nil),        // 2: shardkvpb.TxnRangeKV
	(*TxnWrite)(nil),          // 3: shardkvpb.TxnWrite
	(*TxnRead)(nil),           // 4: shardkvpb.TxnRead
	(*GetRequest)(nil),        // 5: shardkvpb.GetRequest
	(*GetResponse)(nil),       // 6: shardkvpb.GetResponse
	(*PutRequest)(nil),        // 7: shardkvpb.PutRequest
	(*PutResponse)(nil),       // 8: shardkvpb.PutResponse
	(*AppendRequest)(nil),     // 9: shardkvpb.AppendRequest
	(*AppendResponse)(nil),    // 10: shardkvpb.AppendResponse
	(*RangeRequest)(nil),      // 11: shardkvpb.RangeRequest
	(*RangeResponse)(nil),     // 12: shardkvpb.RangeResponse
	(*TxnBeginRequest)(nil),   // 13: shardkvpb.TxnBeginRequest
	(*TxnBeginResponse)(nil),  // 14: shardkvpb.TxnBeginResponse
	(*TxnGetRequest)(nil),     // 15: shardkvpb.TxnGetRequest
	(*TxnGetResponse)(nil),    // 16: shardkvpb.TxnGetResponse
	(*TxnRangeRequest)(nil),   // 17: shardkvpb.TxnRangeRequest
	(*TxnRangeResponse)(nil),  // 18: shardkvpb.TxnRangeResponse
	(*TxnCommitRequest)(nil),  // 19: shardkvpb.TxnCommitRequest
	(*TxnCommitResponse)(nil), // 20: shardkvpb.TxnCommitResponse
}
var file_shardkvpb_shardkv_proto_depIdxs = []int32{
	1,  // 0: shardkvpb.RangeResponse.kvs:type_name -> shardkvpb.KeyValue
	0,  // 1: shardkvpb.TxnBeginRequest.isolation:type_name -> shardkvpb.IsolationLevel
	2,  // 2: shardkvpb.TxnRangeResponse.kvs:type_name -> shardkvpb.TxnRangeKV
	0,  // 3: shardkvpb.TxnCommitRequest.isolation:type_name -> shardkvpb.IsolationLevel
	3,  // 4: shardkvpb.TxnCommitRequest.writes:type_name -> shardkvpb.TxnWrite
	4,  // 5: shardkvpb.TxnCommitRequest.reads:type_name -> shardkvpb.TxnRead
	5,  // 6: shardkvpb.ShardKV.Get:input_type -> shardkvpb.GetRequest
	7,  // 7: shardkvpb.ShardKV.Put:input_type -> shardkvpb.PutRequest
	9,  // 8: shardkvpb.ShardKV.Append:input_type -> shardkvpb.AppendRequest
	11, // 9: shardkvpb.ShardKV.Range:input_type -> shardkvpb.RangeRequest
	13, // 10: shardkvpb.ShardKV.TxnBegin:input_type -> shardkvpb.TxnBeginRequest
	15, // 11: shardkvpb.ShardKV.TxnGet:input_type -> shardkvpb.TxnGetRequest
	17, // 12: shardkvpb.ShardKV.TxnRange:input_type -> shardkvpb.TxnRangeRequest
	19, // 13: shardkvpb.ShardKV.TxnCommit:input_type -> shardkvpb.TxnCommitRequest
	6,  // 14: shardkvpb.ShardKV.Get:output_type -> shardkvpb.GetResponse
	8,  // 15: shardkvpb.ShardKV.Put:output_type -> shardkvpb.PutResponse
	10, // 16: shardkvpb.ShardKV.Append:output_type -> shardkvpb.AppendResponse
	12, // 17: shardkvpb.ShardKV.Range:output_type -> shardkvpb.RangeResponse
	14, // 18: shardkvpb.ShardKV.TxnBegin:output_type -> shardkvpb.TxnBeginResponse
	16, // 19: shardkvpb.ShardKV.TxnGet:output_type -> shardkvpb.TxnGetResponse
	18, // 20: shardkvpb.ShardKV.TxnRange:output_type -> shardkvpb.TxnRangeResponse
	20, // 21: shardkvpb.ShardKV.TxnCommit:output_type -> shardkvpb.TxnCommitResponse
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_shardkvpb_shardkv_proto_init() }
func file_shardkvpb_shardkv_proto_init() {
	if File_shardkvpb_shardkv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shardkvpb_shardkv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shardkvpb_shardkv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxnRangeKV); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shardkvpb_shardkv_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxnWrite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shardkvpb_shardkv_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxnRead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shardkvpb_shardkv_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shardkvpb_shardkv_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shardkvpb_shardkv_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shardkvpb_shardkv_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shardkvpb_shardkv_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppendRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shardkvpb_shardkv_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppendResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shardkvpb_shardkv_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shardkvpb_shardkv_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RangeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shardkvpb_shardkv_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxnBeginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shardkvpb_shardkv_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxnBeginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shardkvpb_shardkv_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxnGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shardkvpb_shardkv_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxnGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shardkvpb_shardkv_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxnRangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shardkvpb_shardkv_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxnRangeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shardkvpb_shardkv_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxnCommitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shardkvpb_shardkv_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxnCommitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shardkvpb_shardkv_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shardkvpb_shardkv_proto_goTypes,
		DependencyIndexes: file_shardkvpb_shardkv_proto_depIdxs,
		EnumInfos:         file_shardkvpb_shardkv_proto_enumTypes,
		MessageInfos:      file_shardkvpb_shardkv_proto_msgTypes,
	}.Build()
	File_shardkvpb_shardkv_proto = out.File
	file_shardkvpb_shardkv_proto_rawDesc = nil
	file_shardkvpb_shardkv_proto_goTypes = nil
	file_shardkvpb_shardkv_proto_depIdxs = nil
}
